version: '1.0'
name: arch-linux-guides
description: arch-linux-guides project
beads:
  default_enabled: true
subjects: {}
auto_detect:
  enabled: true
  method: path_match
project_id: ccc2d782-c74b-450f-a4b9-7f41a5e54eff
